New Feature: send string to specific address

diff --git a/copy_pubkey b/copy_pubkey
--- a/copy_pubkey
+++ b/copy_pubkey
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 #This script saves your public key on the freifunk router. Thus you don't need to type the password anymore
 
@@ -13,6 +13,10 @@ Options:
   --me:           copy my personal public-key (~/.ssh/*.pub)
   --all:          copy all puplic-key stored in ./pubkeys
 
+  --address:      use a specific address instead of 'frei.funk'.
+                  This MUST be the first parameter, if you want to use this.
+                  Supports IPv4 and IPv6.
+
 If you plan to copy many key at once, you should start with your own key:
 
     ./copy_pubkey --me --all
@@ -26,21 +30,39 @@ if [ -z $1 ]; then
   exit 1
 fi
 
+HOSTNAME="frei.funk"
+
 while [ -n "$1" ]; do
   case "$1" in
-    --marc) ssh root@frei.funk "tee -a /etc/dropbear/authorized_keys" < "$PWD""/.pubkeys/marc.pub";;
-    --martin) ssh root@frei.funk "tee -a /etc/dropbear/authorized_keys" < "$PWD""/.pubkeys/martin.pub";;
+    --marc) ssh root@"$HOSTNAME" "tee -a /etc/dropbear/authorized_keys" < "$PWD""/.pubkeys/marc.pub";;
+    --martin) ssh root@"$HOSTNAME" "tee -a /etc/dropbear/authorized_keys" < "$PWD""/.pubkeys/martin.pub";;
     --me)
         #find public key of user
         PUBKEY=$(find ~/.ssh/*.pub -type f)
-        ssh root@frei.funk "tee -a /etc/dropbear/authorized_keys" < "$PUBKEY"
+        ssh root@"$HOSTNAME" "tee -a /etc/dropbear/authorized_keys" < "$PUBKEY"
         ;;
     --all)
-      LIST=$(find "$PWD/.pubkeys/" -type f)
-      for FILE in $LIST; do
-        ssh root@frei.funk "tee -a /etc/dropbear/authorized_keys" < "$FILE"
-      done
-      ;;
+        LIST=$(find "$PWD/.pubkeys/" -type f)
+        for FILE in $LIST; do
+          ssh root@"$HOSTNAME" "tee -a /etc/dropbear/authorized_keys" < "$FILE"
+        done
+        ;;
+    --address)
+        read -p "IP-Adresse des Routers: " ROUTERIP
+
+	checkip4='^(0*(1?[0-9]{1,2}|2([0-4][0-9]|5[0-5]))\.){3}'
+	 checkip4+='0*(1?[0-9]{1,2}|2([0-4][0-9]|5[0-5]))$'
+	checkip6='^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$'
+
+	if [[ "${ROUTERIP}" =~ $checkip4 ]]; then
+	  HOSTNAME="$ROUTERIP"
+	elif [[ "$routerip" =~ $checkip6 ]]; then
+	  HOSTNAME="$ROUTERIP"
+	else
+          echo "Invalid ip-adress"
+	  exit 1
+	fi
+        ;;
     *|-h|--help) help_text
      break;;
   esac
